name: random_chat_flutter_v2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.3
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  formz: ^0.7.0
  google_sign_in: ^6.2.1
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
